# Create data csv file.
## The code

In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
def load_file(filename, label, file_label, delimiter):
    
    # open the file
    with open(filename) as f:
        
        # get the header
        for line in f:
            if line.startswith('Time'):
                break
                
        # convert the header into a list of headings
        header = line.strip('\n').split(delimiter)
        
        # append label and file label to header
        header += ['Label', 'File_Label']
        
        # read in rest of data
        data = []
        for line in f:
            
            # strip the new line character and split using the tab
            
            line = line.strip('\n').split(delimiter) 
            
            # add label and file label to end of line
            line += [str(label), str(file_label)]
            
            # add line to end of data list
            data.append(line)
            
        # convert data list to pandas data frame and return
        frame = pd.DataFrame(data, columns = header)
        return frame

In [3]:
def load_directory(filelist, data_directory, data_filename, delimiter):
    # load the filelist
    filelist = pd.read_csv(filelist)
    
    frames = [] # list to contain frame for each file
    
    # Load each of the files and put the data frame at the end of the frame list
    for i, (file, label) in enumerate(zip(filelist['Filename'], filelist['Label'])):
        full_name = os.path.join(data_directory, file) 
        frame = load_file(full_name, label, i, delimiter) 
        frames.append(frame) 
    
    # concatenate frames into one frame
    frames = pd.concat(frames, sort=False)
        
    # output frame to file
    with open(data_filename, 'w') as f:
        frames.to_csv(f, sep = ',', index=False)

In [9]:
for sub_directory in ['2014']:
    filelist = "filelist_{}.csv".format(sub_directory)
    data_directory = os.path.join(os.curdir, sub_directory)
    data_filename = "data_{}.csv".format(sub_directory)
    delimiter = ',' if sub_directory == 'PSL' else '\t'
    load_directory(filelist, data_directory, data_filename, delimiter)

## The output

In [7]:
# set the label type to string (to allow for 'F')
types = {
    'Label':'str'
}
pd.read_csv("data_PSL.csv", dtype = types)

,Time,FL2 SctInt,Scat_EL1,Scat_EL2,Scat_EL3,Scat_EL4,FL2 SctPk,FL1_280,FL2_280,Pwr_280,...,Size,AF,TotalT2,MeasT2,FT,TPCT1,TotalT1,Label,File_Label,Pw
0,149,216,45,38,54,55,49,308,2112,2047,...,2.00700,2.0180,24.0,20.8,2,0,22.33,1,0,NaN
1,157,196,39,36,49,47,35,336,2112,2047,...,1.53400,2.0500,24.0,20.8,2,0,22.33,1,0,NaN
2,197,186,45,38,55,56,40,354,2112,2047,...,1.72200,1.9630,24.0,20.8,2,0,22.33,1,0,NaN
3,240,186,44,39,53,57,53,317,2112,2047,...,2.11700,2.5080,24.0,20.8,2,0,22.33,1,0,NaN
4,269,191,39,36,50,52,44,328,2112,2047,...,1.85700,1.5130,24.0,20.8,2,0,22.33,1,0,NaN
5,287,149,40,35,53,49,39,340,2112,2047,...,1.68600,1.8770,24.0,20.8,2,0,22.33,1,0,NaN
6,335,22,4,6,5,9,9,196,0,2047,...,0.34540,4.7090,24.0,20.8,2,0,22.33,1,0,NaN
7,351,211,42,40,48,51,46,333,2112,2047,...,1.91900,4.3320,24.0,20.8,2,0,22.33,1,0,NaN
8,360,246,41,38,51,49,48,368,2112,2047,...,1.97900,2.3280,24.0,20.8,2,0,22.33,1,0,NaN
9,392,153,42,35,51,51,36,318,2112,2047,...,1.57300,2.0720,24.0,20.8,2,0,22.33,1,0,NaN
10,421,220,42,39,52,53,48,309,2112,2047,...,1.97900,1.6490,24.0,20.8,2,0,22.33,1,0,NaN
11,448,227,41,36,52,48,46,374,2112,2047,...,1.91900,2.2270,24.0,20.8,2,0,22.33,1,0,NaN
12,504,25,10,8,11,13,11,147,16,2047,...,0.43530,5.0650,24.0,20.8,2,0,22.33,1,0,NaN
13,560,151,42,38,54,51,39,309,2112,2047,...,1.68600,1.2920,24.0,20.8,2,0,22.33,1,0,NaN
14,583,172,44,38,54,58,46,342,2112,2047,...,1.91900,2.8810,24.0,20.8,2,0,22.33,1,0,NaN
15,639,169,44,37,50,50,38,291,2112,2047,...,1.65000,3.3850,24.0,20.8,2,0,22.33,1,0,NaN
16,788,152,42,39,54,54,54,316,2112,2047,...,2.14200,0.8699,24.0,20.8,2,16,22.33,1,0,NaN
17,847,155,39,38,52,52,36,293,2112,2047,...,1.57300,1.8310,38.8,25.4,2,0,36.42,1,0,NaN
18,859,165,43,40,55,57,44,287,2112,2047,...,1.85700,1.7620,38.8,25.4,2,0,36.42,1,0,NaN
19,920,155,40,37,51,52,34,305,2112,2047,...,1.49300,1.0460,38.8,25.4,2,0,36.42,1,0,NaN
20,998,172,42,38,57,51,47,337,2112,2047,...,1.94900,2.3770,38.8,25.4,2,0,36.42,1,0,NaN
21,1023,59,8,5,10,11,23,55,383,2047,...,1.00100,6.3750,38.8,25.4,2,0,36.42,1,0,NaN
22,1034,73,8,5,9,10,22,61,456,2047,...,0.95330,7.0290,38.8,25.4,2,0,36.42,1,0,NaN
23,1044,62,8,8,11,12,19,64,420,2047,...,0.81050,4.0940,38.8,25.4,2,0,36.42,1,0,NaN
24,1053,62,6,8,8,12,18,58,434,2047,...,0.76290,3.8010,38.8,25.4,2,0,36.42,1,0,NaN
25,1062,86,7,10,10,10,23,72,427,2047,...,1.00100,8.5950,38.8,25.4,2,0,36.42,1,0,NaN
26,1075,65,7,6,8,10,23,61,402,2047,...,1.00100,5.0740,38.8,25.4,2,0,36.42,1,0,NaN
27,1085,71,7,5,9,11,19,56,403,2047,...,0.81050,4.7090,38.8,25.4,2,0,36.42,1,0,NaN
28,1092,90,7,6,10,13,25,56,396,2047,...,1.09500,2.5330,38.8,25.4,2,0,36.42,1,0,NaN
29,1099,55,7,6,8,11,20,65,460,2047,...,0.85820,3.8780,38.8,25.4,2,0,36.42,1,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44207,58522,1,1,1,1,2,1,9,0,2047,...,0.01629,-1.0000,0.0,0.0,3,0,0.00,F,9,NaN
44208,59227,0,2,1,2,4,1,6,-4,2047,...,0.01629,-1.0000,0.0,0.0,3,0,0.00,F,9,NaN
44209,59933,0,0,1,2,4,1,13,-3,2047,...,0.01629,-1.0000,0.0,0.0,3,0,0.00,F,9,NaN
44210,60637,0,1,3,2,1,0,4,1,2047,...,0.00000,-1.0000,0.0,0.0,3,0,0.00,F,9,NaN
44211,61342,0,2,3,1,1,0,10,-4,2047,...,0.00000,-1.0000,0.0,0.0,3,0,0.00,F,9,NaN
44212,62048,0,1,2,4,2,1,9,-3,2047,...,0.01629,-1.0000,0.0,0.0,3,0,0.00,F,9,NaN
44213,62752,0,1,1,1,2,1,12,-4,2047,...,0.01629,-1.0000,0.0,0.0,3,0,0.00,F,9,NaN
44214,63458,1,0,1,1,2,1,2,-1,2047,...,0.01629,-1.0000,0.0,0.0,3,0,0.00,F,9,NaN
44215,64162,0,1,2,4,2,0,11,-2,2047,...,0.00000,-1.0000,0.0,0.0,3,0,0.00,F,9,NaN
44216,64868,1,1,1,1,3,1,8,-1,2047,...,0.01629,-1.0000,0.0,0.0,3,0,0.00,F,9,NaN
44217,65573,0,2,2,1,3,0,2,-6,2047,...,0.00000,-1.0000,0.0,0.0,3,0,0.00,F,9,NaN
44218,66277,0,2,3,2,0,0,10,-3,2047,...,0.00000,-1.0000,0.0,0.0,3,0,0.00,F,9,NaN
44219,66983,0,1,1,1,0,0,8,-1,2047,...,0.00000,-1.0000,0.0,0.0,3,0,0.00,F,9,NaN
44220,67688,0,3,2,2,3,1,12,-2,2047,...,0.01629,-1.0000,0.0,0.0,3,0,0.00,F,9,NaN
44221,68394,0,1,1,3,1,1,7,-3,2047,...,0.01629,-1.0000,0.0,0.0,3,0,0.00,F,9,NaN
44222,69098,1,0,2,2,2,0,9,0,2047,...,0.00000,-1.0000,0.0,0.0,3,0,0.00,F,9,NaN
44223,69803,0,1,2,1,4,0,10,-3,2047,...,0.00000,-1.0000,0.0,0.0,3,0,0.00,F,9,NaN
44224,70509,1,1,1,3,3,1,5,0,2047,...,0.01629,-1.0000,0.0,0.0,3,0,0.00,F,9,NaN
44225,71213,1,2,2,5,3,1,-1,-3,2047,...,0.01629,-1.0000,0.0,0.0,3,0,0.00,F,9,NaN
44226,71919,1,1,4,3,3,0,11,0,2047,...,0.00000,-1.0000,0.0,0.0,3,0,0.00,F,9,NaN
44227,72623,0,1,2,2,2,1,8,-2,2047,...,0.01629,-1.0000,0.0,0.0,3,0,0.00,F,9,NaN
44228,73329,0,0,1,1,3,1,2,-3,2047,...,0.01629,-1.0000,0.0,0.0,3,0,0.00,F,9,NaN
44229,74034,0,1,1,2,3,1,13,-1,2047,...,0.01629,-1.0000,0.0,0.0,3,0,0.00,F,9,NaN
44230,74738,0,3,2,2,3,0,12,-7,2047,...,0.00000,-1.0000,0.0,0.0,3,0,0.00,F,9,NaN
44231,75444,0,3,0,3,1,0,8,-1,2047,...,0.00000,-1.0000,0.0,0.0,3,0,0.00,F,9,NaN
44232,76149,0,2,4,2,2,0,15,-6,2047,...,0.00000,-1.0000,0.0,0.0,3,0,0.00,F,9,NaN
44233,76855,0,1,1,3,2,0,20,5,2047,...,0.00000,-1.0000,0.0,0.0,3,0,0.00,F,9,NaN
44234,77559,0,1,0,1,3,1,7,1,2047,...,0.01629,-1.0000,0.0,0.0,3,0,0.00,F,9,NaN
44235,78265,1,2,1,1,3,1,16,-2,2047,...,0.01629,-1.0000,0.0,0.0,3,0,0.00,F,9,NaN
44236,78970,1,0,2,2,5,1,9,-5,2047,...,0.01629,-1.0000,0.0,0.0,3,0,0.00,F,9,NaN