In [60]:
def load_data(filename):
    # set the label type to string (to allow for 'F')
    types = {
        'Label':'str'
    }
    df = pd.read_csv(filename, dtype = types)
    return df

df = load_data('data_PSL.csv')
filelist = pd.read_csv("filelist_PSL.csv")

In [24]:
# Quick check that sample sizes correspond with what is published 
# in Crawford, 2015
filelist[['Short Name', 'Label']]

             Short Name Label
0   Green $1\mu$m PSL I     1
1  Green $1\mu$m PSL II     1
2    Blue $2.1\mu$m PSL     2
3     Red $2.2\mu$m PSL     3
4   Green $3.1\mu$m PSL     4
5      $4.17\mu$m PSL I     5
6     $4.17\mu$m PSL II     5
7    $4.17\mu$m PSL III     5
8                   NaN     F
9                   NaN     F

In [25]:
df.groupby('Label').size()

Label
1    5055
2    8796
3    8942
4    7976
5    8927
F    4541
dtype: int64

In [26]:
def prepare_data(df):
    df = reduce_columns(df)
    return(df)

In [49]:
def split_frame(df):
    data = df.loc[df['Label'] != 'F']
    FT = df.loc[df['Label'] == 'F']
    return data, FT

def reduce_columns(df):
    required_columns = ['FL1_280', 'FL2_280', 'FL2_370', 'Size', 'AF']
    return df[required_columns]

def size_threshold(df, threshold = 0.8):
    return df.filter()

def standardise(df, method = 'zscore'):
    if method == 'zscore':
        return (data - data.mean(axis = 0))/(data.std(axis = 0))
    elif method == 'range':
        return (data - data.min(axis=0))/(data.max(axis = 0)-data.min(axis=0))

data, FT = split_frame(df)

,Time,FL2 SctInt,Scat_EL1,Scat_EL2,Scat_EL3,Scat_EL4,FL2 SctPk,FL1_280,FL2_280,Pwr_280,...,Size,AF,TotalT2,MeasT2,FT,TPCT1,TotalT1,Label,File_Label,Pw
39696,705,0,2,2,1,1,1,4,-4,2047,...,0.01629,-1.0,2738.0,119.6,3,0,2488.00,F,8,NaN
39697,1409,0,3,1,2,4,0,6,-4,2047,...,0.00000,-1.0,2288.0,100.0,3,0,2050.00,F,8,NaN
39698,2115,0,1,1,2,2,1,8,-2,2047,...,0.01629,-1.0,1818.0,79.2,3,0,1640.00,F,8,NaN
39699,2819,1,1,2,2,4,1,11,0,2047,...,0.01629,-1.0,1320.0,58.8,3,0,1180.00,F,8,NaN
39700,3525,1,2,1,2,2,1,19,0,2047,...,0.01629,-1.0,877.0,39.2,3,0,827.30,F,8,NaN
39701,4230,0,2,1,2,1,1,9,-1,2047,...,0.01629,-1.0,460.6,20.4,3,0,477.50,F,8,NaN
39702,4934,0,1,2,3,4,1,7,-2,2047,...,0.01629,-1.0,52.0,2.2,3,0,74.85,F,8,NaN
39703,5640,0,2,1,2,5,1,11,-1,2047,...,0.01629,-1.0,0.0,0.0,3,0,65.65,F,8,NaN
39704,6345,0,0,0,1,5,1,16,-7,2047,...,0.01629,-1.0,0.0,0.0,3,0,0.00,F,8,NaN
39705,7051,0,2,1,3,3,1,9,-3,2047,...,0.01629,-1.0,0.0,0.0,3,0,0.00,F,8,NaN
39706,7755,0,1,3,2,1,0,8,-4,2047,...,0.00000,-1.0,0.0,0.0,3,0,0.00,F,8,NaN
39707,8461,1,3,1,1,3,1,7,-7,2047,...,0.01629,-1.0,0.0,0.0,3,0,0.00,F,8,NaN
39708,9165,0,2,1,1,4,0,6,-2,2047,...,0.00000,-1.0,0.0,0.0,3,0,0.00,F,8,NaN
39709,9870,0,2,0,1,3,1,-2,-5,2047,...,0.01629,-1.0,0.0,0.0,3,0,0.00,F,8,NaN
39710,10576,0,2,1,2,3,1,13,1,2047,...,0.01629,-1.0,0.0,0.0,3,0,0.00,F,8,NaN
39711,11280,0,1,2,2,3,1,16,0,2047,...,0.01629,-1.0,0.0,0.0,3,0,0.00,F,8,NaN
39712,11986,1,2,0,1,3,1,5,-4,2047,...,0.01629,-1.0,0.0,0.0,3,0,0.00,F,8,NaN
39713,12691,0,1,3,1,3,1,12,2,2047,...,0.01629,-1.0,0.0,0.0,3,0,0.00,F,8,NaN
39714,13397,1,0,1,3,2,1,3,-1,2047,...,0.01629,-1.0,0.0,0.0,3,0,0.00,F,8,NaN
39715,14101,0,1,0,2,4,1,2,-2,2047,...,0.01629,-1.0,0.0,0.0,3,0,0.00,F,8,NaN
39716,14806,0,2,2,2,0,1,9,-5,2047,...,0.01629,-1.0,0.0,0.0,3,0,0.00,F,8,NaN
39717,15512,1,5,2,1,2,1,0,-5,2047,...,0.01629,-1.0,0.0,0.0,3,0,0.00,F,8,NaN
39718,16216,0,0,2,2,3,0,3,-4,2047,...,0.00000,-1.0,0.0,0.0,3,0,0.00,F,8,NaN
39719,16922,0,2,1,1,1,0,13,-1,2047,...,0.00000,-1.0,0.0,0.0,3,0,0.00,F,8,NaN
39720,17626,0,3,1,3,2,1,5,-4,2047,...,0.01629,-1.0,0.0,0.0,3,0,0.00,F,8,NaN
39721,18332,0,3,1,1,3,0,10,-5,2047,...,0.00000,-1.0,0.0,0.0,3,0,0.00,F,8,NaN
39722,19037,0,1,1,1,3,1,14,-5,2047,...,0.01629,-1.0,0.0,0.0,3,0,0.00,F,8,NaN
39723,19741,0,1,3,1,1,1,15,-7,2047,...,0.01629,-1.0,0.0,0.0,3,0,0.00,F,8,NaN
39724,20447,1,1,2,1,3,0,13,-4,2047,...,0.00000,-1.0,0.0,0.0,3,0,0.00,F,8,NaN
39725,21152,1,1,1,2,5,1,4,-1,2047,...,0.01629,-1.0,0.0,0.0,3,0,0.00,F,8,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44207,58522,1,1,1,1,2,1,9,0,2047,...,0.01629,-1.0,0.0,0.0,3,0,0.00,F,9,NaN
44208,59227,0,2,1,2,4,1,6,-4,2047,...,0.01629,-1.0,0.0,0.0,3,0,0.00,F,9,NaN
44209,59933,0,0,1,2,4,1,13,-3,2047,...,0.01629,-1.0,0.0,0.0,3,0,0.00,F,9,NaN
44210,60637,0,1,3,2,1,0,4,1,2047,...,0.00000,-1.0,0.0,0.0,3,0,0.00,F,9,NaN
44211,61342,0,2,3,1,1,0,10,-4,2047,...,0.00000,-1.0,0.0,0.0,3,0,0.00,F,9,NaN
44212,62048,0,1,2,4,2,1,9,-3,2047,...,0.01629,-1.0,0.0,0.0,3,0,0.00,F,9,NaN
44213,62752,0,1,1,1,2,1,12,-4,2047,...,0.01629,-1.0,0.0,0.0,3,0,0.00,F,9,NaN
44214,63458,1,0,1,1,2,1,2,-1,2047,...,0.01629,-1.0,0.0,0.0,3,0,0.00,F,9,NaN
44215,64162,0,1,2,4,2,0,11,-2,2047,...,0.00000,-1.0,0.0,0.0,3,0,0.00,F,9,NaN
44216,64868,1,1,1,1,3,1,8,-1,2047,...,0.01629,-1.0,0.0,0.0,3,0,0.00,F,9,NaN
44217,65573,0,2,2,1,3,0,2,-6,2047,...,0.00000,-1.0,0.0,0.0,3,0,0.00,F,9,NaN
44218,66277,0,2,3,2,0,0,10,-3,2047,...,0.00000,-1.0,0.0,0.0,3,0,0.00,F,9,NaN
44219,66983,0,1,1,1,0,0,8,-1,2047,...,0.00000,-1.0,0.0,0.0,3,0,0.00,F,9,NaN
44220,67688,0,3,2,2,3,1,12,-2,2047,...,0.01629,-1.0,0.0,0.0,3,0,0.00,F,9,NaN
44221,68394,0,1,1,3,1,1,7,-3,2047,...,0.01629,-1.0,0.0,0.0,3,0,0.00,F,9,NaN
44222,69098,1,0,2,2,2,0,9,0,2047,...,0.00000,-1.0,0.0,0.0,3,0,0.00,F,9,NaN
44223,69803,0,1,2,1,4,0,10,-3,2047,...,0.00000,-1.0,0.0,0.0,3,0,0.00,F,9,NaN
44224,70509,1,1,1,3,3,1,5,0,2047,...,0.01629,-1.0,0.0,0.0,3,0,0.00,F,9,NaN
44225,71213,1,2,2,5,3,1,-1,-3,2047,...,0.01629,-1.0,0.0,0.0,3,0,0.00,F,9,NaN
44226,71919,1,1,4,3,3,0,11,0,2047,...,0.00000,-1.0,0.0,0.0,3,0,0.00,F,9,NaN
44227,72623,0,1,2,2,2,1,8,-2,2047,...,0.01629,-1.0,0.0,0.0,3,0,0.00,F,9,NaN
44228,73329,0,0,1,1,3,1,2,-3,2047,...,0.01629,-1.0,0.0,0.0,3,0,0.00,F,9,NaN
44229,74034,0,1,1,2,3,1,13,-1,2047,...,0.01629,-1.0,0.0,0.0,3,0,0.00,F,9,NaN
44230,74738,0,3,2,2,3,0,12,-7,2047,...,0.00000,-1.0,0.0,0.0,3,0,0.00,F,9,NaN
44231,75444,0,3,0,3,1,0,8,-1,2047,...,0.00000,-1.0,0.0,0.0,3,0,0.00,F,9,NaN
44232,76149,0,2,4,2,2,0,15,-6,2047,...,0.00000,-1.0,0.0,0.0,3,0,0.00,F,9,NaN
44233,76855,0,1,1,3,2,0,20,5,2047,...,0.00000,-1.0,0.0,0.0,3,0,0.00,F,9,NaN
44234,77559,0,1,0,1,3,1,7,1,2047,...,0.01629,-1.0,0.0,0.0,3,0,0.00,F,9,NaN
44235,78265,1,2,1,1,3,1,16,-2,2047,...,0.01629,-1.0,0.0,0.0,3,0,0.00,F,9,NaN
44236,78970,1,0,2,2,5,1,9,-5,2047,...,0.01629,-1.0,0.0,0.0,3,0,0.00,F,9,NaN